### ISSUE TITLE
Question - Make a video call with Verto

### ISSUE THREAD

**Issue by DeividVeloso** [signalwire/signalwire-node#245] opened 2020-04-03 14:33 UTC
Hi guys!

I'm trying to do a video call with **Verto.ts** and verto module.

I could do a video call using **Relay/Signalwire**, but **I couldn't do a video call with Verto.**

Using **Verto.ts** I only could show the local video image, **but the remote video didn't show**. I use **the same code that Relay use on vanilla-calling/index.html**

**Verto**
```
 function connect() {
      client = new Verto({
        host: host,
        login: `${document.getElementById('username').value}@${host}`,
        password: document.getElementById('password').value,
      });

    const STUN_SERVER = { urls: stun };
    const TURN_SERVER = {
      urls: turn,
      username: *****,
      credential: ****,
    };
    client.iceServers = [TURN_SERVER, STUN_SERVER];

      // client.autoRecoverCalls = false;
      client.remoteElement = 'remoteVideo';
      client.localElement = 'localVideo';

        if (document.getElementById('audio').checked) {
        client.enableMicrophone()
      } else {
        client.disableMicrophone()
      }
      if (document.getElementById('video').checked) {
        client.enableWebcam()
      } else {
        client.disableWebcam()
      }
         .....
```

With this VERTO code, I could do a call and receive a call, speak, hang up, connect and disconnect, but **only show local video** and I need to show both Local and Remote video. 

![image](https://user-images.githubusercontent.com/16343871/78368602-3c948080-759a-11ea-9622-033e9a80ed5c.png)

When I pick the call **the remote video doesn't show image** stay this black way, **but I can speak and listen to my voice.**

It seems that is setting localStream and remoteStream to localVideo.srcObject and  remoteVideo.srcObject correctly.

![Set Remote](https://user-images.githubusercontent.com/16343871/78399450-45517a80-75cb-11ea-8289-88ecdc36aa6e.png)

```
{type: "callUpdate", call: t}
type: "callUpdate"
call: t
nodeId: (...)
localStream: MediaStream
remoteStream: MediaStream
memberChannel: (...)
session: n
reconnectDelay: (...)
devices: (...)
videoDevices: (...)
audioInDevices: (...)
audioOutDevices: (...)
mediaConstraints: (...)
iceServers: (...)
speaker: (...)
localElement: (...)
remoteElement: (...)
__logger: (...)
connected: (...)
expired: (...)
options: {host: "**********", login: "*************", password: "******"}
uuid: "f34a354c-331d-4c61-93ee-5a2b5ee17fcf"
sessionid: "7352da4e-f0c0-4346-8a3c-5e759073f855"
subscriptions: {}
expiresAt: 0
signature: null
relayProtocol: "verto-protocol"
contexts: []
timeoutErrorCode: -329990
connection: e {session: n, _wsClient: WebSocket, _host: "wss://***********", _timers: {…}, upDur: null, …}
_jwtAuth: true
_doKeepAlive: false
_autoReconnect: true
_idle: false
_executeQueue: []
_onSocketOpen: ƒ ()
_onSocketCloseOrError: ƒ ()
_onSocketMessage: ƒ ()
_handleLoginError: ƒ ()
_checkTokenExpiration: ƒ ()
calls: {}
autoRecoverCalls: true
_iceServers: (2) [{…}, {…}]
_localElement: video#localVideo.w-100
_remoteElement: video#remoteVideo.w-100
_devices: {}
_audioConstraints: true
_videoConstraints: true
_speaker: null
__proto__: t
id: "e712f66c-cbcb-47a9-8e11-83dd692d55c8"
state: "destroy"
prevState: "hangup"
channels: []
role: "participant"
extension: null
_state: 10
_prevState: 9
gotAnswer: true
gotEarly: true
_lastSerno: 0
_targetNodeId: null
_iceTimeout: null
_iceDone: true
_checkConferenceSerno: ƒ (e)
options: {destinationNumber: "sip:********.com", remoteCallerName: "Outbound Call", remoteCallerNumber: "sip:********.com", callerName: "", callerNumber: "", …}
_onMediaError: ƒ ()
_statsInterval: null
direction: "outbound"
peer: null
cause: "NORMAL_CLEARING"
causeCode: 16
__proto__: e
__proto__: Object
```

**Using Relay with this code**

```
 function connect() {
      client = new Relay({
        project: document.getElementById('project').value,
        token: document.getElementById('token').value
      });

      // client.autoRecoverCalls = false;
      client.remoteElement = 'remoteVideo';
      client.localElement = 'localVideo';

      if (document.getElementById('audio').checked) {
        client.enableMicrophone()
      } else {
        client.disableMicrophone()
      }
      if (document.getElementById('video').checked) {
        client.enableWebcam()
      } else {
        client.disableWebcam()
      }
```

**Worked perfectly showing both videos Remote and Local**

![signal](https://user-images.githubusercontent.com/16343871/78371135-eb868b80-759d-11ea-89e5-3fe0a1e96d92.png)

**Could you help me do video local and remote work in Verto, please?**

Thank you so much.

**Comment by DeividVeloso** [comment] 2020-04-06 13:55
Maybe I have a clue, I compare the logs between Verto calls and Relay calls and I got these differences:

Verto WebRTC logs:
I didn't see **video references** when createAnswer
```
{
     "time": "4/4/2020, 9:32:54 PM",
     "type": "createAnswer",
     "value": "options: {, voiceActivityDetection: true}"
    },
    {
     "time": "4/4/2020, 9:32:54 PM",
     "type": "createAnswerOnSuccess",
     "value": "type: answer, sdp: v=0\r\no=- 6138768697774791730 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS aFsdTQxU9GBCJiGFx5V5jMMy0VvCgZ2plTmQ\r\nm=audio 9 RTP/SAVPF 0\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:3vHD\r\na=ice-pwd:6fHOftr+JeiZ11VakjHE4toe\r\na=ice-options:trickle\r\na=fingerprint:sha-256 11:66:E5:85:F7:89:02:77:D0:07:B0:B0:2B:D7:2F:5D:0F:CE:5B:3C:14:29:18:E4:5B:3D:2D:E6:76:60:B1:95\r\na=setup:active\r\na=mid:audio\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:0 PCMU/8000\r\na=ssrc:2691934058 cname:dacs3EAIfuKa5Tr0\r\na=ssrc:2691934058 msid:aFsdTQxU9GBCJiGFx5V5jMMy0VvCgZ2plTmQ 48152418-7636-4c6d-8435-fabdc8d8bf73\r\na=ssrc:2691934058 mslabel:aFsdTQxU9GBCJiGFx5V5jMMy0VvCgZ2plTmQ\r\na=ssrc:2691934058 label:48152418-7636-4c6d-8435-fabdc8d8bf73\r\n"
    },
    {
     "time": "4/4/2020, 9:32:54 PM",
     "type": "setLocalDescription",
     "value": "type: answer, sdp: v=0\r\no=- 6138768697774791730 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS aFsdTQxU9GBCJiGFx5V5jMMy0VvCgZ2plTmQ\r\nm=audio 9 RTP/SAVPF 0\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:3vHD\r\na=ice-pwd:6fHOftr+JeiZ11VakjHE4toe\r\na=ice-options:trickle\r\na=fingerprint:sha-256 11:66:E5:85:F7:89:02:77:D0:07:B0:B0:2B:D7:2F:5D:0F:CE:5B:3C:14:29:18:E4:5B:3D:2D:E6:76:60:B1:95\r\na=setup:active\r\na=mid:audio\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:0 PCMU/8000\r\na=ssrc:2691934058 cname:dacs3EAIfuKa5Tr0\r\na=ssrc:2691934058 msid:aFsdTQxU9GBCJiGFx5V5jMMy0VvCgZ2plTmQ 48152418-7636-4c6d-8435-fabdc8d8bf73\r\na=ssrc:2691934058 mslabel:aFsdTQxU9GBCJiGFx5V5jMMy0VvCgZ2plTmQ\r\na=ssrc:2691934058 label:48152418-7636-4c6d-8435-fabdc8d8bf73\r\n"
    },
    {
     "time": "4/4/2020, 9:32:54 PM",
     "type": "signalingStateChange",
     "value": "SignalingStateStable"
    },
    {
     "time": "4/4/2020, 9:32:54 PM",
     "type": "setLocalDescriptionOnSuccess",
     "value": ""
    },
    {
     "time": "4/4/2020, 9:32:54 PM",
     "type": "iceGatheringStateChange",
     "value": "gathering"
    },
    {
     "time": "4/4/2020, 9:32:54 PM",
     "type": "iceConnectionStateChange",
     "value": "checking"
    },
    {
     "time": "4/4/2020, 9:32:54 PM",
     "type": "connectionStateChange",
     "value": "connecting"
    },
    {
     "time": "4/4/2020, 9:32:54 PM",
     "type": "onIceCandidate",
     "value": "sdpMid: audio, sdpMLineIndex: 0, candidate: candidate:3693621629 1 udp 2113937151 192.168.15.18 59595 typ host generation 0 ufrag 3vHD network-cost 999"
    },
    {
     "time": "4/4/2020, 9:32:54 PM",
     "type": "onIceCandidate",
     "value": "sdpMid: audio, sdpMLineIndex: 0, candidate: candidate:3734154586 1 udp 2113939711 2804:431:c7d8:265:c0fb:8c82:943c:b36d 59596 typ host generation 0 ufrag 3vHD network-cost 999"
    },
    {
     "time": "4/4/2020, 9:32:55 PM",
     "type": "iceConnectionStateChange",
     "value": "connected"
    },
    {
     "time": "4/4/2020, 9:32:55 PM",
     "type": "iceGatheringStateChange",
     "value": "complete"
    },
    {
     "time": "4/4/2020, 9:32:56 PM",
     "type": "connectionStateChange",
     "value": "connected"
    },
    {
     "time": "4/4/2020, 9:33:09 PM",
     "type": "stop",
     "value": ""
    },
    {
     "time": "4/4/2020, 9:33:09 PM",
     "type": "connectionStateChange",
     "value": "closed"
    }
   ],
```

In Relay I can see video references:

```
 {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "createAnswer",
     "value": "options: {, voiceActivityDetection: true}"
    },
    {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "createAnswerOnSuccess",
     "value": "type: answer, sdp: v=0\r\no=- 1151137027383953843 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS SlgdVvtoVOYTunXHuwm2KChC99ujba2NK2Kq\r\nm=audio 9 RTP/SAVPF 102 0 8\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:CWbo\r\na=ice-pwd:s3U7hBW1Y1gATvwhGNWZgHp7\r\na=ice-options:trickle\r\na=fingerprint:sha-256 53:15:B3:1B:6D:D0:60:47:9F:C4:9F:05:BA:F6:05:9A:4D:9C:3F:F6:B6:A3:57:4C:96:B1:5C:B4:58:12:E2:85\r\na=setup:active\r\na=mid:audio\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:102 opus/48000/2\r\na=fmtp:102 minptime=10;useinbandfec=1\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=ssrc:217366022 cname:ABf0cX7r74S/uuBU\r\na=ssrc:217366022 msid:SlgdVvtoVOYTunXHuwm2KChC99ujba2NK2Kq 6e5b9454-d6d0-4a4e-9c25-208295bd676e\r\na=ssrc:217366022 mslabel:SlgdVvtoVOYTunXHuwm2KChC99ujba2NK2Kq\r\na=ssrc:217366022 label:6e5b9454-d6d0-4a4e-9c25-208295bd676e\r\nm=video 9 RTP/SAVPF 96 103 104\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:js5f\r\na=ice-pwd:f+VnpqdYzIpxuIKNoY3vobeW\r\na=ice-options:trickle\r\na=fingerprint:sha-256 53:15:B3:1B:6D:D0:60:47:9F:C4:9F:05:BA:F6:05:9A:4D:9C:3F:F6:B6:A3:57:4C:96:B1:5C:B4:58:12:E2:85\r\na=setup:active\r\na=mid:video\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:103 VP9/90000\r\na=rtcp-fb:103 ccm fir\r\na=rtcp-fb:103 nack\r\na=rtcp-fb:103 nack pli\r\na=fmtp:103 profile-id=0\r\na=rtpmap:104 H264/90000\r\na=rtcp-fb:104 ccm fir\r\na=rtcp-fb:104 nack\r\na=rtcp-fb:104 nack pli\r\na=fmtp:104 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f\r\na=ssrc:1296520594 cname:ABf0cX7r74S/uuBU\r\na=ssrc:1296520594 msid:SlgdVvtoVOYTunXHuwm2KChC99ujba2NK2Kq 5b7da50b-bbaa-4a02-a3ef-cab639f74780\r\na=ssrc:1296520594 mslabel:SlgdVvtoVOYTunXHuwm2KChC99ujba2NK2Kq\r\na=ssrc:1296520594 label:5b7da50b-bbaa-4a02-a3ef-cab639f74780\r\n"
    },
    {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "setLocalDescription",
     "value": "type: answer, sdp: v=0\r\no=- 1151137027383953843 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=msid-semantic: WMS SlgdVvtoVOYTunXHuwm2KChC99ujba2NK2Kq\r\nm=audio 9 RTP/SAVPF 102 0 8\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:CWbo\r\na=ice-pwd:s3U7hBW1Y1gATvwhGNWZgHp7\r\na=ice-options:trickle\r\na=fingerprint:sha-256 53:15:B3:1B:6D:D0:60:47:9F:C4:9F:05:BA:F6:05:9A:4D:9C:3F:F6:B6:A3:57:4C:96:B1:5C:B4:58:12:E2:85\r\na=setup:active\r\na=mid:audio\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:102 opus/48000/2\r\na=fmtp:102 minptime=10;useinbandfec=1\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=ssrc:217366022 cname:ABf0cX7r74S/uuBU\r\na=ssrc:217366022 msid:SlgdVvtoVOYTunXHuwm2KChC99ujba2NK2Kq 6e5b9454-d6d0-4a4e-9c25-208295bd676e\r\na=ssrc:217366022 mslabel:SlgdVvtoVOYTunXHuwm2KChC99ujba2NK2Kq\r\na=ssrc:217366022 label:6e5b9454-d6d0-4a4e-9c25-208295bd676e\r\nm=video 9 RTP/SAVPF 96 103 104\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:js5f\r\na=ice-pwd:f+VnpqdYzIpxuIKNoY3vobeW\r\na=ice-options:trickle\r\na=fingerprint:sha-256 53:15:B3:1B:6D:D0:60:47:9F:C4:9F:05:BA:F6:05:9A:4D:9C:3F:F6:B6:A3:57:4C:96:B1:5C:B4:58:12:E2:85\r\na=setup:active\r\na=mid:video\r\na=sendrecv\r\na=rtcp-mux\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:103 VP9/90000\r\na=rtcp-fb:103 ccm fir\r\na=rtcp-fb:103 nack\r\na=rtcp-fb:103 nack pli\r\na=fmtp:103 profile-id=0\r\na=rtpmap:104 H264/90000\r\na=rtcp-fb:104 ccm fir\r\na=rtcp-fb:104 nack\r\na=rtcp-fb:104 nack pli\r\na=fmtp:104 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f\r\na=ssrc:1296520594 cname:ABf0cX7r74S/uuBU\r\na=ssrc:1296520594 msid:SlgdVvtoVOYTunXHuwm2KChC99ujba2NK2Kq 5b7da50b-bbaa-4a02-a3ef-cab639f74780\r\na=ssrc:1296520594 mslabel:SlgdVvtoVOYTunXHuwm2KChC99ujba2NK2Kq\r\na=ssrc:1296520594 label:5b7da50b-bbaa-4a02-a3ef-cab639f74780\r\n"
    },
    {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "signalingStateChange",
     "value": "SignalingStateStable"
    },
    {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "setLocalDescriptionOnSuccess",
     "value": ""
    },
    {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "iceGatheringStateChange",
     "value": "gathering"
    },
    {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "iceConnectionStateChange",
     "value": "checking"
    },
    {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "connectionStateChange",
     "value": "connecting"
    },
    {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "onIceCandidate",
     "value": "sdpMid: audio, sdpMLineIndex: 0, candidate: candidate:3693621629 1 udp 2113937151 192.168.15.18 58509 typ host generation 0 ufrag CWbo network-cost 999"
    },
    {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "onIceCandidate",
     "value": "sdpMid: audio, sdpMLineIndex: 0, candidate: candidate:3734154586 1 udp 2113939711 2804:431:c7d8:265:c0fb:8c82:943c:b36d 58510 typ host generation 0 ufrag CWbo network-cost 999"
    },
    {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "onIceCandidate",
     "value": "sdpMid: video, sdpMLineIndex: 1, candidate: candidate:3693621629 1 udp 2113937151 192.168.15.18 61968 typ host generation 0 ufrag js5f network-cost 999"
    },
    {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "onIceCandidate",
     "value": "sdpMid: video, sdpMLineIndex: 1, candidate: candidate:3734154586 1 udp 2113939711 2804:431:c7d8:265:c0fb:8c82:943c:b36d 61969 typ host generation 0 ufrag js5f network-cost 999"
    },
    {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "iceGatheringStateChange",
     "value": "complete"
    },
    {
     "time": "4/4/2020, 9:02:24 PM",
     "type": "iceConnectionStateChange",
     "value": "connected"
    },
    {
     "time": "4/4/2020, 9:02:25 PM",
     "type": "connectionStateChange",
     "value": "connected"
    },


```

How can I fix this when using Verto? I saw that the code is almost the same, each one extends from **BrowserSession**.

**Comment by edolix** [comment] 2020-04-06 14:30
Hi @DeividVeloso, 

looking SDPs from your last comment it seems that one side is not offering `video` but only `audio`.
What type of device are you trying to call? 

I'm going to change the title of the issue since this is not a bug with the SDK 👍

**Comment by DeividVeloso** [comment] 2020-04-06 14:35
I'm calling to the browser using SIP call, I called from one browser to another using the same network

I got another clue, in the object **this.options** when I try to **set _setLocalDescription** the property **remoteSdp** has this value when using Verto

```
"v=0
o=FreeSWITCH 1586160261 1586160262 IN IP4 64.16.248.54
s=FreeSWITCH
c=IN IP4 64.16.248.54
t=0 0
a=msid-semantic: WMS PxCQ1hsgK1ddyYcYW8K7ZXeMnUuwa9SP
m=audio 21690 RTP/SAVPF 0
a=rtpmap:0 PCMU/8000
a=fingerprint:sha-256 75:78:13:DE:40:31:3C:B6:C5:80:2F:74:50:A3:B0:76:30:28:0F:9B:FE:FA:DE:08:8F:9B:24:1A:74:76:8F:3F
a=setup:actpass
a=rtcp-mux
a=rtcp:21690 IN IP4 64.16.248.54
a=ssrc:2192079911 cname:wkwosOv3Gy65m9T8
a=ssrc:2192079911 msid:PxCQ1hsgK1ddyYcYW8K7ZXeMnUuwa9SP a0
a=ssrc:2192079911 mslabel:PxCQ1hsgK1ddyYcYW8K7ZXeMnUuwa9SP
a=ssrc:2192079911 label:PxCQ1hsgK1ddyYcYW8K7ZXeMnUuwa9SPa0
a=ice-ufrag:7t5XhazvUUSUUAAh
a=ice-pwd:LWw3BRW7fT2sSLqQ5mDdm3y6
a=candidate:0358365192 1 udp 659136 64.16.248.54 21690 typ host generation 0
a=candidate:0358365192 2 udp 659136 64.16.248.54 21690 typ host generation 0
a=silenceSupp:off - - - -
a=ptime:20
a=sendrecv
```

**Using Relay has this other value**
```
"v=0
o=FreeSWITCH 1586168728 1586168729 IN IP4 157.245.82.149
s=FreeSWITCH
c=IN IP4 157.245.82.149
t=0 0
a=msid-semantic: WMS VcOCWPGwW4WQL6YKSvL9zHAl4MmZI1lt
m=audio 14456 RTP/SAVPF 102 0 8
a=rtpmap:102 opus/48000/2
a=fmtp:102 useinbandfec=1; maxaveragebitrate=30000; maxplaybackrate=48000; ptime=20; minptime=10; maxptime=40
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=fingerprint:sha-256 1B:41:49:E0:67:C5:36:DC:8A:A9:D3:1F:F7:C4:DA:04:AB:0E:6B:4A:8D:53:66:13:7E:B9:BF:7E:41:6B:FD:3C
a=setup:actpass
a=rtcp-mux
a=rtcp:14456 IN IP4 157.245.82.149
a=ssrc:982760584 cname:4ZWQFtdsoZ8ZWWzF
a=ssrc:982760584 msid:VcOCWPGwW4WQL6YKSvL9zHAl4MmZI1lt a0
a=ssrc:982760584 mslabel:VcOCWPGwW4WQL6YKSvL9zHAl4MmZI1lt
a=ssrc:982760584 label:VcOCWPGwW4WQL6YKSvL9zHAl4MmZI1lta0
a=ice-ufrag:iaEHI5TCH5sfXDzR
a=ice-pwd:smyYFCgUseJe18Ka9fHHaraH
a=candidate:8759580099 1 udp 659136 157.245.82.149 14456 typ host generation 0
a=candidate:8759580099 2 udp 659136 157.245.82.149 14456 typ host generation 0
a=silenceSupp:off - - - -
a=ptime:20
a=sendrecv
m=video 14458 RTP/SAVPF 96 103 104
b=AS:1024
a=rtpmap:96 VP8/90000
a=rtpmap:103 VP9/90000
a=rtpmap:104 H264/90000
a=sendrecv
a=fingerprint:sha-256 1B:41:49:E0:67:C5:36:DC:8A:A9:D3:1F:F7:C4:DA:04:AB:0E:6B:4A:8D:53:66:13:7E:B9:BF:7E:41:6B:FD:3C
a=setup:actpass
a=rtcp-mux
a=rtcp:14458 IN IP4 157.245.82.149
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 ccm tmmbr
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:103 ccm fir
a=rtcp-fb:103 ccm tmmbr
a=rtcp-fb:103 nack
a=rtcp-fb:103 nack pli
a=rtcp-fb:104 ccm fir
a=rtcp-fb:104 ccm tmmbr
a=rtcp-fb:104 nack
a=rtcp-fb:104 nack pli
a=ssrc:189690376 cname:4ZWQFtdsoZ8ZWWzF
a=ssrc:189690376 msid:VcOCWPGwW4WQL6YKSvL9zHAl4MmZI1lt v0
a=ssrc:189690376 mslabel:VcOCWPGwW4WQL6YKSvL9zHAl4MmZI1lt
a=ssrc:189690376 label:VcOCWPGwW4WQL6YKSvL9zHAl4MmZI1ltv0
a=ice-ufrag:ZJ0zIvsLApFDXzFA
a=ice-pwd:2edLOoIGbHj1o07eAXE9jWKK
a=candidate:9355850943 1 udp 659136 157.245.82.149 14458 typ host generation 0
a=candidate:9355850943 2 udp 659135 157.245.82.149 14458 typ host generation 0
a=end-of-candidates

```

I saw that when using Verto it doesn't put video inside SDP on remote, but when using Relya it puts video inside SDP

What can be?

Thanks

**Comment by edolix** [comment] 2020-04-06 14:45
Might be your FreeSWITCH configuration while using Verto. That means the caller is not offering video.

Did you set up FS yourself?

**Comment by bryanrite** [comment] 2020-04-06 16:36
Since this is not a bug with the SDK, I'm going to close this ticket, but please feel free to get help on the SignalWire Slack Community: https://signalwire.community/

There are lots of community members and SignalWire support staff that can help out with questions.

Thanks!

**Closed by bryanrite** 2020-04-06 16:36 UTC
Labels: area/js, feedback/question
