### ISSUE TITLE
Getting error Cannot read property 'close' of null     at Connection.close when on server

### ISSUE THREAD

**Issue by khanani92** [signalwire/signalwire-node#160] opened 2019-08-20 07:36 UTC
Whenever I stop my nodejs server it gives me this error.
(node:4036) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of null
    at Connection.close (/home/khanani92/Development/client-work/pannucomp/poem_backend/node_modules/@signalwire/node/dist/common/src/services/Connection.js:100:24)
    at RelayClient._removeConnection (/home/khanani92/Development/client-work/pannucomp/poem_backend/node_modules/@signalwire/node/dist/common/src/BaseSession.js:260:29)
    at RelayClient.<anonymous> (/home/khanani92/Development/client-work/pannucomp/poem_backend/node_modules/@signalwire/node/dist/common/src/BaseSession.js:106:18)
    at Generator.next (<anonymous>)
    at fulfilled (/home/khanani92/Development/client-work/pannucomp/poem_backend/node_modules/@signalwire/node/dist/common/src/BaseSession.js:4:58)

**Comment by edolix** [comment] 2019-08-20 08:05
Hi @khanani92! 

Are you on the latest version of `@signalwire/node`? In your script, are you using a Relay Consumer or a client?  
Thanks!

**Comment by khanani92** [comment] 2019-08-20 08:17
@edolix  I'm using 
"@signalwire/node": "^2.1.0"

And I'm using Client 
 const client = new RelayClient({
   project: 'xxxxxxxxxx',
   token: 'XXXXX'
 });

**Comment by edolix** [comment] 2019-08-20 09:43
@khanani92 i'm not able to reproduce it. To stop the server are you sending `SIGINT` to it? This error happens every time you stop the client?

Please, double check your package version inside node_modules too.

**Comment by khanani92** [comment] 2019-08-20 14:13
I'm not sending SIGINT fro stopping the server. I'm using visual code debugger to run server. Secondly yeah every time. Even my colleges are also getting same error

**Comment by edolix** [comment] 2019-08-20 15:41
@khanani92 can you share your code (or a snippet with i can reproduce the issue) and explain a bit your process?

I'm also using the debugger but i can't see that error between breakpoints.

**Comment by khanani92** [comment] 2019-08-22 06:24
```
const { RelayClient } = require('@signalwire/node');
let client = new RelayClient({
  project: 'xxxxxxxxxxxxxxxx',
  token: 'YYYYYYYYYYYYYYYY'
});

async function sendSMS(smsOptions) {
  try {
    await client.connect();
    client
      .on('signalwire.ready', async client => {
        // Your client is ready!
        const sendResult = await client.messaging.send({
          context: 'office',
          from: smsOptions.from,
          to: smsOptions.to,
          body: smsOptions.text
        });

        if (sendResult.successful) {
          console.log('Message ID: ', sendResult.messageId);
        }
        client.disconnect();
        return sendResult;
      })
      .on('signalwire.error', error => {
        // Got an error...
        throw error;
      });
    // return info.messageId;
  } catch (e) {
    throw e;
  }
}
```
This the code of my sms service. I'm getting the sms successfully when using this service

**Comment by edolix** [comment] 2019-08-22 09:49
@khanani92 it looks a bit weird you connect/disconnect a RelayClient for **each** message since the client should be a long-running process to interact with Relay in real time.

I'd advise you to start using a [Relay Consumer](https://docs.signalwire.com/topics/relay-sdk-nodejs/v2/#relay-sdk-for-node-js-using-the-sdk-relay-consumer) (read also the [Consumer API](https://docs.signalwire.com/topics/relay-sdk-nodejs/v2/#api-reference-relay-consumer)). 

Using a Consumer you will have a separated process running along side your application and you can send to it several [Relay Tasks](https://docs.signalwire.com/topics/relay-sdk-nodejs/v2/#api-reference-relay-task) to deliver SMS.

A quick Consumer that listen for the `example` context:

> consumer.js
```javascript
const { RelayConsumer } = require('@signalwire/node')

const consumer = new RelayConsumer({
  project: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',
  token: 'PTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  contexts: ['example'], // You can listen for several contexts too
  onTask: async (smsOptions) => {

    // Handle your task: send the SMS
    const sendResult = await consumer.client.messaging.send({
      context: smsOptions.context,
      from: smsOptions.from,
      to: smsOptions.to,
      body: smsOptions.text
    });

    if (sendResult.successful) {
      console.log('Message ID: ', sendResult.messageId);
      // Update your system with the messageId
    }

  }
})

consumer.run()
```


Then deliver a Task on the `example` context from your service:

> yourService.js
```javascript
const { Task } = require('@signalwire/node');

async function sendSMS(smsOptions) {
  const yourTask = new Task('XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX', 'PTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
  // smsOptions will be delivered to one of your Consumer so it must have a structure like:
  // {
  //   context: '',
  //   from: '',
  //   to: '',
  //   text: ''
  // }
  try {
    await yourTask.deliver('example', smsOptions) 
  } catch (error) {
    console.error('Error during deliver Task', error)
  }
}
```

With this setup you will be able to have multiple Consumers (each on its own different process), handle multiple `contexts` and scale them horizontally without problems.


At the end, If this infrastructure is over-complicated for your requirements, i'd advise you to try our [RestClient](https://docs.signalwire.com/topics/laml-api/#api-reference-messages-create-a-message) to deliver SMS using the REST APIs instead of `Relay`.

As a side note: i see some issues in your code (in addition to what described above)... 

1. You should attach the `signalwire.ready` listener **before** call `client.connect()`. See the [example in the connect docs.](https://docs.signalwire.com/topics/relay-sdk-nodejs/v2/#api-reference-relay-client-methods-connect)
2. You should `await` the `client.disconnect()` too.

**Comment by edolix** [comment] 2019-08-26 08:11
Hi @khanani92 i'm going to close this one. 

Feel free to reopen it if you need more info, thanks!

**Closed by edolix** 2019-08-26 08:11 UTC
Labels: area/node, area/node/relay, feedback/question
